### ISSUE TITLE
RQESService Configuration

### ISSUE THREAD

**Issue by pcg92** [eu-digital-identity-wallet/eudi-lib-android-rqes-core#12]
Hello,

I'm currently setting up the RQESService using the following initial configuration in my project:

```
val rqesService = RQESService(
    serviceEndpointUrl = "https://example.com/csc/v2",
    config = CSCClientConfig(
        client = OAuth2Client.Confidential.ClientSecretBasic(
            clientId = "client-id",
            clientSecret = "client-secret"
        ),
        authFlowRedirectionURI = URI("rqes:redirect"),
        scaBaseURL = URL("https://example.com"),
    ),
    hashAlgorithm = HashAlgorithmOID.SHA_256,
    signingAlgorithm = SigningAlgorithmOID.RSA_SHA256,
    httpClientFactory = {
        HttpClient(/* Configuration Details */)
    }
)
```

Is there a test server available for the serviceEndpointUrl and other URLs used in this configuration? If not, could you provide guidance on how to set up my own test environment?

It's a complex project and I might not fully understand it, but wouldn't it be possible for an Android app to sign directly without going through a server, just by connecting with the wallet?

Thank you!

**Comment by vkanellopoulos** [comment]
Hi @pcg92 

Thank you for reporting this issue!

The requested serviceEndpointUrl can be found on the following page:

https://eudiw.dev/

Please visit the page to retrieve the endpoint URL and adjust your configuration accordingly. Let us know if you need further assistance!

**Comment by pcg92** [comment]
Thank you for the response. I wonder if in the future there will be any free and open service like "https://trustprovider.signer.eudiw.dev/" or will private companies have to set up their own? In OAuth2Client, what data needs to be entered?
I'm asking because I'm interested in creating an app for signing documents with the European ID.
